# Generated by Django 4.2 on 2023-04-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_turma', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoMateriaHorarioProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('tipo_recorrencia', models.CharField(max_length=255)),
                ('codigo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoAlunoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=255)),
                ('codigo_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia')),
            ],
        ),
    ]
